name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: registry.patr.cloud
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
      - name: Build and push
        run: docker build . -t registry.patr.cloud/397098526bd54271b9cb6ef92fce0ce5/my:latest
      - name: Test
        run: docker push registry.patr.cloud/397098526bd54271b9cb6ef92fce0ce5/my:latest
